# This file is used to run your application locally with Docker Compose

version: '3.8'
services:
  strapi-template-ingress:
    container_name: strapi-template-ingress
    image: nginx:stable-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:9999:80"
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"

  strapi-template-server:
    container_name: strapi-template-server
    build:
      context: ./server
      dockerfile: ${dockerfile}
      args:
        USER_UID: ${taito_host_user_uid}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
      - "127.0.0.1:4229:9229"
    volumes:
      - "./server:/develop:delegated"
      - "/develop/node_modules"
    secrets:
      - DATABASE_PASSWORD
      - BUCKET_KEY_ID
      - BUCKET_KEY_SECRET
      - ADMIN_JWT_SECRET
      - JWT_SECRET
      - APP_KEYS
      - API_TOKEN_SALT
    environment:
      # Paths and bind
      BASE_PATH: /api
      API_PORT: 8080
      API_BINDADDR: 0.0.0.0
      COMMON_PUBLIC_PORT: 9999
      COMMON_URL: http://localhost:9999
      # Common variables
      COMMON_COMPANY: companyname
      COMMON_PROJECT: strapi-template
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local

      # Services
      SENTRY_DSN: #sentryDSN
      ADMIN_JWT_SECRET_FILE: /run/secrets/ADMIN_JWT_SECRET
      JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      APP_KEYS_FILE: /run/secrets/APP_KEYS
      API_TOKEN_SALT_FILE: /run/secrets/API_TOKEN_SALT

      # Use dev database instead of local
      DATABASE_HOST: strapi-template-database
      DATABASE_PORT: ${db_database_port}
      DATABASE_NAME: ${db_database_name}
      DATABASE_USER: ${db_database_mgr_username}
      DATABASE_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD
      DATABASE_POOL_MIN: "1"
      DATABASE_POOL_MAX: "10"
      DATABASE_SSL_ENABLED: "${db_database_ssl_enabled}"
      DATABASE_SSL_CLIENT_CERT_ENABLED: "${db_database_ssl_client_cert_enabled}"
      DATABASE_SSL_SERVER_CERT_ENABLED: "${db_database_ssl_server_cert_enabled}"

      # Use dev bucket instead of local
      BUCKET_BUCKET: ${st_bucket_name}
      BUCKET_REGION: ${taito_provider_region}
      BUCKET_BASE_URL: https://storage.googleapis.com/${taito_random_name}-dev # For GCP
      BUCKET_ENDPOINT: https://storage.googleapis.com # For GCP
      # BUCKET_ENDPOINT: http://${taito_project}-${taito_env}-storage:9000/ # For Azure through S3 proxy
      # BUCKET_FORCE_PATH_STYLE: "true"
      BUCKET_KEY_ID_FILE: /run/secrets/BUCKET_KEY_ID
      BUCKET_KEY_SECRET_FILE: /run/secrets/BUCKET_KEY_SECRET


  # "EXTERNAL RESOURCES"

  # Use dev database instead of local
  strapi-template-database:
    container_name: strapi-template-database
    image: ${taito_image:-ghcr.io/taitounited/taito-cli:latest}
    restart: unless-stopped
    entrypoint: /bin/sh -c "cd /project && taito db-proxy:dev 5432"
    user: taito
    networks:
      - default
    ports:
      - "127.0.0.1:6001:5432"
    volumes:
      - ".:/project:delegated"
      # Mount cloud credentials for db proxy
      - "${HOME}/.aws:/home/taito/.aws"
      - "${HOME}/.azure:/home/taito/.azure"
      - "${HOME}/.config/doctl:/home/taito/.config/doctl"
      - "${HOME}/.config/gcloud:/home/taito/.config/gcloud"
      - "${HOME}/.kube:/home/taito/.kube"
    environment:
      taito_docker: "true"

secrets:
  DATABASE_PASSWORD:
    file: ./secrets/${taito_env}/${db_database_mgr_secret}
  BUCKET_KEY_ID:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-storage.accessKeyId
  BUCKET_KEY_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-storage.secretKey
  ADMIN_JWT_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-strapi.adminJwtSecret
  JWT_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-strapi.jwtSecret
  APP_KEYS:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-strapi.appKeys
  API_TOKEN_SALT:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-strapi.apiTokenSalt

networks:
  default:
